### PR TITLE
Add version to composer.json file

### PR DESCRIPTION
**Pull request by miogalang**
Add version to composer.json file

/cc @jwswj @joseconsador @mmolina @atroche

### References
* JIRA:

### Risks
* None

### CODE REVIEW

**Comment by miogalang** [comment]
https://packagist.org/packages/zendesk/zendesk_api_client_php#2.x-dev

We are already available on composer. What we need now is to add a tag after merging v2 onto master and to cleanup the old branches

**Comment by miogalang** [comment]
Added merge commits to make v2 mergeable into master once this has been merge onto v2

**Comment by jwswj** [comment]
:+1:

**Comment by joseconsador** [comment]
:+1:

**Pull request merged**
