### PR TITLE
Add ticket audits and ticket audits test

### PR DESCRIPTION
**Pull request by miogalang**
Added ticket audits class and added tests

/cc @joseconsador @jwswj @mmolina @atroche 

### References
 - Jira link: 

### Risks
 - The audit endpoint might not work correctly (low)

### CODE REVIEW

**Comment by joseconsador** [comment]
:+1:

**Comment by miogalang** [comment]
Updated to use new version of guzzle

:haircut:
@joseconsador @jwswj @mmolina @atroche

**Comment by joseconsador** [comment]
:+1:

**Comment by jwswj** [comment]
:+1:

**Pull request merged**
