### PR TITLE
add support for listing articles for a specific section

### PR DESCRIPTION
**Pull request by asifiqbal91**
## Add API support for getting articles list of a specific section.

**REF: [https://developer.zendesk.com/rest_api/docs/help_center/articles#list-articles](url)**

> List Articles endpoints:
> GET /api/v2/help_center/sections/{id}/articles.json
> GET /api/v2/help_center/{locale}/sections/{id}/articles.json

### CODE REVIEW

**Comment by kcasas** [comment]
Hi @asifiqbal91,

Please create unit tests for the functionality you added and ensure travis build passes. For more info, please read our [Contribution Guidelines](https://github.com/zendesk/zendesk_api_client_php/blob/master/CONTRIBUTING.md).

Thanks for the interest :)

**Comment by asifiqbal91** [comment]
Hi @kcasas 
I have updated some Test Cases. But travis build not passed yet. I am not so familiar this workflow.

Thank you. :-)

**Comment by kcasas** [comment]
@asifiqbal91 You can click on the `red x button` and can view the travis console output from there. [Here](https://travis-ci.org/zendesk/zendesk_api_client_php/jobs/256854630) is the console output for one of the failed travis build. It seems that you are not following the `PSR2` coding standard.

**Comment by jmramos02** [comment]
Hello @asifiqbal91 you can also click `details` down below to check where your tests are failing

**Comment by asifiqbal91** [comment]
@jmramos02 
It says, **no environment variables set** I am not good enough on TBD.

**Comment by kcasas** [comment]
@asifiqbal91 Got a closer look at the travis builds and it seems like the problem is not with your changes. I guess `PSR2` got stricter this past few days and it affected some of the existing core code. I've created a PR #347 that fixes this. Sorry about that.

**Comment by kcasas** [comment]
@asifiqbal91 We've merge the `PSR2` fixes. Rebase your branch for travis to go green.

**Comment by asifiqbal91** [comment]
I got green on Pull #351
So, I am closing this pull request

**Comment by asifiqbal91** [comment]
Hi @kcasas please check #351

**Pull request closed without merging**
