### PR TITLE
Feature/sessions api's

### PR DESCRIPTION
**Pull request by tobz-nz**
Add support for the sessions api's.

### CODE REVIEW

**Comment by ggrossman** [comment]
Thanks for your contribution @tobz-nz , we'll review it shortly. Thanks for the tip about [mockery](https://packagist.org/packages/mockery/mockery). Agreed this test suite is far from ideal and we hope to rework it when we have more resources to do so.

**Comment by shanitang** [comment]
@tobz-nz
Since we just merge some updates for the unit tests, it would be perfect if you could add the session test to it. Thank would be really helpful!! Thank you!!

**Comment by atroche** [comment]
@tobz-nz this looks like really good code. can you get the Travis build passing before we merge it?

**Comment by jwswj** [comment]
Sessions have been added in v2 - https://github.com/zendesk/zendesk_api_client_php/blob/master/src/Zendesk/API/Resources/Core/Sessions.php

**Pull request closed without merging**
