### PR TITLE
Allow guzzle 7

### PR DESCRIPTION
**Pull request by gmponos**
Hi,

We have recently tagged a new version 7 of guzzle.

https://github.com/guzzle/guzzle/releases/tag/7.0.0

🎉

### CODE REVIEW

**Comment by aglipanci** [comment]
@miogalang can you please merge this?

**Comment by ipalaus** [comment]
Can we get merged in? We can't update our app to Laravel 8 because we're using this package https://packagist.org/packages/huddledigital/zendesk-laravel and it's failing because Guzzle requirements on the underlying API (this repository). It's just a wrapper around and Laravel 8 now requires Guzzle 7.0.

**Comment by aglipanci** [comment]
I spoke with Zendesk Support and it seems like this package is no longer being maintained.

**Comment by ipalaus** [comment]
Thanks for the heads up!

**Comment by derekps** [comment]
Adding more support to this. This is a very simple change that will allow compatibility with Laravel 8

**Comment by ahmednasir91** [comment]
Indeed its a small change and required by many customers should be merged to unblock upgrade to laravel 8.0 @miogalang

**Comment by derekps** [comment]
Tagging top contributors

@miogalang @joseconsador @atroche @devarispbrown

**Review by nogates — APPROVED** [review]

**Comment by gkatechis** [comment]
Hi all! I just wanted to let you know that we will be merging this soon, we're just working on figuring out exactly how to handle some things internally, since this repo is technically no longer maintained by us. Thanks for your patience and we'll provide an update soon!

**Comment by gkatechis** [comment]
This update has been merged and I've bumped the latest version to 2.2.10

Thanks again all for your patience with this!

**Pull request merged**
