### PR TITLE
Bug fix Issue #430

### PR DESCRIPTION
**Pull request by thisishassan**
index.php is updated to fix bug #430.

Broken link has been updated to match the file name present in the samples

### CODE REVIEW

**Comment by thisishassan** [comment]
All that i did was to update a broken link present on index file. Yet it seems like the build failed for PHP 5.5 on travis-ci.
Thought there we no such changes which could have altered or effected execution in any way. So, kindly look into this.

**Comment by jmramos02** [comment]
Looks like an update to the travis needs to be done. `5.4` and `5.5` can be set to `trusty` https://github.com/travis-ci/travis-ci/issues/9881

**Comment by jmramos02** [comment]
I have a fix for travis here: https://github.com/zendesk/zendesk_api_client_php/pull/432
I updated the travis file to use trusty as the dist, so php 5.5 can run smoothly.

**Comment by jmramos02** [comment]
@thisishassan if my fix gets merged, you can now to proceed with this PR :)

**Pull request closed without merging**
