### PR TITLE
Initial add for Articles

### PR DESCRIPTION
**Pull request by patrickconroy**
Right now there's no way to interact with Articles. This starts that. If I'm going in the right direction I'll flesh this out with the other methods in this PR, not expecting this to get merged like this just waiting for feedback.

Thanks

### CODE REVIEW

**Comment by jwswj** [comment]
Hey @patrickconroy - we're currently working a refreshed version of the API which will improve the stability and coverage of endpoints for the API client - https://github.com/zendesk/zendesk_api_client_php/pull/99

**Comment by jwswj** [comment]
https://gist.github.com/atroche/c88328cdfa91d4c4b0e3 is where we are heading, but any feedback would be very welcome on https://github.com/zendesk/zendesk_api_client_php/issues/89

**Comment by patrickconroy** [comment]
Thanks guys. I guess for now I'll close this and wait for v2. I'll use my fork of master so I can get articles.

**Comment by jwswj** [comment]
@patrickconroy v2 is now merged into master and in beta. @joseconsador added support for the Help Center namespace, however we haven't been able to built out all of these endpoints yet. Hopefully the new structure will make it a lot easier.

**Pull request closed without merging**
