### PR TITLE
ha-quidco: fix problem ticket listing

### PR DESCRIPTION
**Pull request by ha-quidco**
Hi, I've fixed a bug with the listing of problem tickets:
https://developer.zendesk.com/rest_api/docs/core/tickets#listing-ticket-problems

Would be great to get this to > main > composer asap.

Regards,
Hartmut

### CODE REVIEW

**Comment by ha-quidco** [comment]
Any news on this?

**Comment by buheryfi** [comment]
Hey Hartmut,
By the way, what was the problem you were encountering and why did you make the changes you did?
Sincerely,
James Peterson

**Comment by ha-quidco** [comment]
Hi buheryfi,
As you can see when comparing the code, the used endpoint was simply wrong..

**Comment by buheryfi** [comment]
Hi Hartmut,
Just so we can make it easier for the maintainers of the repo to understand why the changes were made, I'd like to clarify that the URL used in the function was tickets/$id/problems.json, when actually it should be just problems.json.  No ID parameter is needed.  One minor modification that I would suggest is keeping the  parameter type set to array in Line 393, unless you removed that for a reason as well?

 public function problems($params) => public function problems(array $params)

Sincerely,
James Peterson

**Comment by ha-quidco** [comment]
Hi James,

thanks for the review and pointing out the missing parameter type set. It had been removed by accident, not by purpose. I've fixed the fork.

Apologise for the brief initial comment, it was a very busy day...

Regards,
Hartmut

PS: the following method *problemAutoComplete* is probably broken as well.
To correct the end point may be enough to fix it, but I don't know how to test for I've got no clue what it's supposed to do... :-)

**Comment by buheryfi** [comment]
Hi Hartmut,
I also see that there is no test for problemAutoComplete and for listProblems method specifically.  You can read more about what they are supposed to do in the Zendesk API developer docs for each method.
https://developer.zendesk.com/rest_api/docs/core/tickets#listing-ticket-problems
https://developer.zendesk.com/rest_api/docs/core/tickets#autocomplete-problems

 If you would like to build the test for those methods, that would be great.  You can follow the pattern established with the other methods in the TicketsTest file - https://github.com/zendesk/zendesk_api_client_php/blob/master/tests/Zendesk/API/LiveTests/TicketsTest.php

Sincerely,
James Peterson

**Comment by ha-quidco** [comment]
Hi James,

There's nothing explained in https://developer.zendesk.com/rest_api/docs/core/tickets#autocomplete-problems ...

I'm afraid I don't have time to create tests now. I've done last time when I added new methods, but I can't do now - while I would appreciate if it still could be merged.

Maybe I can add tests next week when I've got some spare time. But as far as I can see you are working for zendesk?!? ;-)

Regards,
Hartmut

**Comment by buheryfi** [comment]
Hi Hartmut,

You are correct that I am working for Zendesk.  I don't work on this project, but I do like to spend my time here contributing as I can. ;-)  Just trying to help communication in any way I can.  I don't have any control over merging pull requests, so we'll have to wait for the maintainers of the repo to have a look.

Sincerely,
James Peterson

**Comment by shanitang** [comment]
Hi Hartmut @ha-quidco,
You are right. The endpoint in `problems` is wrong. Thanks for your work, and sorry for the late reply.

@buheryfi Thanks for reviewing this :)

**Comment by ha-quidco** [comment]
thanks a lot @shanitang!

**Pull request merged**
