### PR TITLE
Fix deprecated stream_for GuzzleHttp\Psr7

### PR DESCRIPTION
**Pull request by DanielGSoftware**
[https://docs.aws.amazon.com/aws-sdk-php/v3/api/function-GuzzleHttp.Psr7.stream_for.html](https://docs.aws.amazon.com/aws-sdk-php/v3/api/function-GuzzleHttp.Psr7.stream_for.html)

Use Utils instead

### CODE REVIEW

**Comment by jprodrigues70** [comment]
Please, accept this PR. Your project is broken.

**Comment by gabrielpeixoto** [comment]
👌

**Comment by cuongthetran** [comment]
+1

**Comment by ecoologic** [comment]
This solution has already been implemented. Thank you for your contribution.

**Pull request closed without merging**
