### PR TITLE
Zendesk Sell API and Contacts resource support

### PR DESCRIPTION
**Pull request by Alex-Sh**
Added Sell API "Contacts" endpoint support
https://developers.getbase.com/docs/rest/reference/contacts

### CODE REVIEW

**Comment by Alex-Sh** [comment]
The only thing here is Zendesk Sell have different endpoint so HttpClient should be created like this:
``` 
$client = new HttpClient('', '', 'https', 'api.getbase.com');
$client->setAuth('oauth', ['token' => 'TOKEN']);
```

**Comment by AxelDeneu** [comment]
Is it possible to merge this PR ? Pretty useful if you use Sell API.

**Comment by ecoologic** [comment]
Hi,

 thank you for your request,
are you still interested in a solution for this issue?

**Comment by ecoologic** [comment]
Closing due to inactivity. Re-open if needed.

**Comment by AxelDeneu** [comment]
Sorry, I missed your comment. I'm still interested in a solution for this issue.

**Comment by ecoologic** [comment]
Hi Alex, no worries. Thanks for your contribution.

**Comment by AxelDeneu** [comment]
Thank you too!
If needed, I can contribute on this PR, I don't know if @Alex-Sh is still interested into but I am. So if I can help in any kind, tell me.

**Comment by token-cjg** [comment]
Thank you for your contribution @Alex-Sh, I have accepted your suggestion in this PR: https://github.com/zendesk/zendesk_api_client_php/pull/537.

**Pull request merged**
