### PR TITLE
[MI-171] Add coding standard to readme

### PR DESCRIPTION
**Pull request by miogalang**
Add the coding standard psr2 to the readme

/cc @jwswj @joseconsador @mmolina @atroche

### References
* JIRA: https://zendesk.atlassian.net/browse/MI-171

### Risks
* None

### CODE REVIEW

**Comment by joseconsador** [comment]
:+1:

**Comment by miogalang** [comment]
:construction:

**Comment by atroche** [comment]
nice

On Thu, Jul 9, 2015 at 12:55 PM, Mio Miguel Galang <notifications@github.com

**Comment by miogalang** [comment]
@atroche is that a :+1: ? haha

**Comment by atroche** [comment]
:+1:

**Comment by miogalang** [comment]
@atroche Awesome Thanks!

**Comment by jwswj** [comment]
Nice!

**Pull request merged**
