### PR TITLE
Use BasicTest::assertEndpointCalled() for most mocked tests

### PR DESCRIPTION
**Pull request by joseconsador**
Use a wrapper function to assert the API client functionality. This removes a lot of repetitive test code.

/cc @miogalang @jwswj @mmolina @atroche

### References
 - Jira link: 

### Risks
 - Medium - the tests might not cover all cases

### CODE REVIEW

**Comment by miogalang** [comment]
:+1: @joseconsador 's commit

**Comment by jwswj** [comment]
This does reduce repetitive code, but it also makes it a little more complicated in my mind. I'm not 100% convinced.

**Comment by miogalang** [comment]
Yes this adds a layer of complexity. But for me it is worth it for readability.

Basically all that is in the code is. This snippet of code would call this endpoint with these parameters. 

It would make the tests easier to understand and removes a lot of the unnecessary lines of code from the test cases.

**Comment by jwswj** [comment]
@danielstjules I hear you've done a fair bit of php in the past. What are your thoughts?

**Comment by jwswj** [comment]
:+1:

**Comment by danielstjules** [comment]
@jwswj [Data providers](https://phpunit.de/manual/current/en/phpunit-book.html#writing-tests-for-phpunit.data-providers) might be helpful for some test classes, helping reduce some of the repetitive testing boilerplate.

**Comment by danielstjules** [comment]
LGTM: :)

**Pull request merged**
