### PR TITLE
Move clearing of sideload to send utility method

### PR DESCRIPTION
**Pull request by miogalang**
Move clearing of sideload to every request made to reduce repeating code

/cc @jwswj @joseconsador @mmolina @atroche

### References
* JIRA:

### Risks
* Low. Sideloading might not work

### CODE REVIEW

**Comment by joseconsador** [comment]
:+1:

**Comment by jwswj** [comment]
Are there any tests for this functionality?

**Comment by joseconsador** [comment]
@jwswj There's ResourceTest::testSideLoad() that does some testing if sideloads are set.

**Comment by jwswj** [comment]
What about an example test of sideloading for a ticket? This is key functionality that we need to make sure is stable for the client.

**Comment by miogalang** [comment]
What I did here is add a test to check the clearing of the sideload after the query.

There is and existing test for tickets sideloading. `TicketsTest::testAllSideLoadedMethod` and `TicketsTest::testAllSideLoadedParameter` which test for using the `sideload()` method and passing it as a parameter to `findAll(['sideload' => 'something'])` respectively.

**Comment by jwswj** [comment]
:+1:

**Pull request merged**
