### PR TITLE
[MI-742] Resolve PHPdoc inconsistencies in resource classes

### PR DESCRIPTION
**Pull request by samgavinio**
/cc @zendesk/mintegrations

### Description

Update return types and method annotations in several resources.

### References
* JIRA: https://zendesk.atlassian.net/browse/MI-742

### Risks
* [low] PHPdocs may be incorrect.

### CODE REVIEW

**Comment by samgavinio** [comment]
@miogalang related to https://github.com/zendesk/zendesk_api_client_php/issues/218.

We could do `stdClass|null`. All this is coming from the call to json_decode.

**Comment by miogalang** [comment]
👍

**Comment by jmramos02** [comment]
👍

**Comment by joseconsador** [comment]
👍

**Comment by miogalang** [comment]
@samgavinio yeah we should do `stdClass|null` that would be better as it is more specific. `mixed` doesn't really tell you much.

**Comment by samgavinio** [comment]
@miogalang I'll open another PR to address #218. Code base is mostly returning `mixed`, I'll do it separately.

**Pull request merged**
