### PR TITLE
Implemented support of sections in help center

### PR DESCRIPTION
**Pull request by LionelLaffineur**
This change adds support of the sections area of the help center.

### CODE REVIEW

**Comment by joseconsador** [comment]
@LionelLaffineur Unit tests would be ❤️

**Comment by LionelLaffineur** [comment]
@joseconsador Can you guide me a bit, I couldn't find why 1 test failed ...

**Comment by joseconsador** [comment]
@LionelLaffineur sure! could you post the travis build or add the test here?

**Comment by LionelLaffineur** [comment]
@joseconsador Here is the link to the build ... strange: now it shows all tests as successful !
https://travis-ci.org/zendesk/zendesk_api_client_php/builds/219617319

**Comment by jmramos02** [comment]
@LionelLaffineur i rerun it to know if it was a flaky test, Looks like it is, will investigate this :)

**Comment by LionelLaffineur** [comment]
@jmramos02 @joseconsador May I ask you why you didn't include it in the release 2.1.10 ?  It has passed the tests and it is useful as it closes the hole in between the categories and the articles ...

**Comment by joseconsador** [comment]
@LionelLaffineur Thanks for this, it really is useful. We need unit tests for the resources you made so we can merge this. We'd be glad to help you!

**Comment by LionelLaffineur** [comment]
@jmramos02   @joseconsador Dears, may I ask you when I could expect this branch to be merged with the master release ?  I would like to get my project back to the master branch so I can get the benefits of the new versions but cannot unitl sections is part of it ?

**Comment by jmramos02** [comment]
Hi @LionelLaffineur can you add unit tests please?

**Comment by LionelLaffineur** [comment]
Hi @jmramos02, yes ... if you can guide me a bit ... I have no idea how to do so !

**Comment by kcasas** [comment]
@LionelLaffineur You can read our [contribution guidelines](https://github.com/zendesk/zendesk_api_client_php/blob/master/CONTRIBUTING.md). We use phpunit and we already have existing tests on `tests/Zendesk`. Your contribution is greatly appreciated. Hope to see more in the future. :)

**Comment by LionelLaffineur** [comment]
@kcasas I have added a new test for the sections and it seems to have passed: https://travis-ci.org/zendesk/zendesk_api_client_php/builds/244548068.

**Comment by jmramos02** [comment]
Looks good to me 👍 @kcasas

**Comment by samgavinio** [comment]
Hi @LionelLaffineur noticed that the create section method doesn't work here because a category_id has to be passed in. I opened a new PR to fix this here: https://github.com/zendesk/zendesk_api_client_php/pull/339

As soon, we get that merged, we'll release a new tag with this. Thanks for your contribution!

**Pull request merged**
